### ISSUE TITLE
Error in prio command

### ISSUE THREAD

**Issue by enannos** [mobitel-ltd/jira-to-matrix#160]
Hello,

we are not able to change the priority of an issue. The following error appears:

2019-3-13 14:19:30,302 - error: [/timeline-handler/index.js] Error in event handling
Error in Matrix prio command
Error in POST request http://jira/rest/api/2/issue/BSP-23, status is 405, body is {"update":{"priority":[{"set":{"id":"3"}}]}}
Event sent to !cGQdMjQKaVdHVQMpXZ:chatserver with event id $155248677022igLTK:chatserver
setting pendingEvent status to sent in !cGQdMjQKaVdHVQMpXZ:chatserver

Can you help us on this?

**Comment by grigori-gru** [comment]
Hello! 
Can you send your Jira API version? For example `v2` or `v3`? Is it come from cloud Jira?

**Comment by grigori-gru** [comment]
I've found reason, it's fixed, https://github.com/mobitel-ltd/jira-to-matrix/pull/161
