### ISSUE TITLE
Mapping JIRA Projects -> Matrix Rooms

### ISSUE THREAD

**Issue by CRCinAU** [mobitel-ltd/jira-to-matrix#181]
I'd like to try and map certain JIRA projects to specific Matrix rooms.

As such, if we have PROJECT-134, that will end up in a room like 'project' in Matrix.

Is this possible at the moment? It seems that if we're only creating rooms per JIRA ticket (not scalable for us) - but I'd like to put one project per room.

I have no problems doing this mapping in the config file, but it doesn't quite seem possible yet?

**Comment by w1r0x** [comment]
We have such mapping, it will triggered by creating epic in a project. Project lead will be invited to room.
But in that room you will see only changes affected by epics, not tasks and stories.

**Comment by CRCinAU** [comment]
Hmmm - that wouldn't really work for our workflows - as users themselves lodge JIRA tickets. As such, the majority of tickets never have an epic, or any linked tickets to them.

We'd have a few people in a room, then just want the basics sent to the room for any ticket in a project. It also means customer updates would end up in the room too...

**Comment by w1r0x** [comment]
Can't understand what functionality do you want from "jira projects -> matrix rooms". You want notifications about all activity in project? Like activity stream at jira dashboard?

**Comment by CRCinAU** [comment]
Pretty much - we have small teams working on different projects - so we have a room dedicated to each project. We don't do rooms per ticket etc.

As such, we might have:
PROJECTA-* -> locationx-devs matrix room
PROJECTB-* -> locationy-devs matrix room
PROJECTC-* -> java-devs matrix room
PROJECTD-* -> customer service matrix room

Then JIRA tickets as, say, PROJECTD-1234

These will very rarely have an epic task type - and the members of different rooms may be mostly the same - but the rooms are divided to stop a single room being a 'catch all' scenario for everything.

As an example, PROJECTD-1234 may be something about a printer not working.

**Comment by w1r0x** [comment]
I think at this case it is pretty easy to write your own stuff. 
We have more complex solution for medium size and big projects. Main idea is to connect all issues on all levels together, to avoid using jira interface and use matrix rooms instead.
