### ISSUE TITLE
Errno 7

### ISSUE THREAD

**Issue by linuxgoose** [mobitel-ltd/jira-to-matrix#195]
Hello,

I am trying to do 'npm run start' but I am getting the following errors:

11/15/2019, 6:32:26 AM,769 - warn: [/src/app.js] Jira Bot stopped  
{
  message: "EISDIR: illegal operation on a directory, open 'logs/service'",
  stack: "Error: EISDIR: illegal operation on a directory, open 'logs/service'",
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: 'logs/service'
}
11/15/2019, 6:32:26 AM,772 - info: [/fsm/index.js] Jira server close

/home/n0maint/jira-to-matrix/node_modules/javascript-state-machine/lib/state-machine.js:530
    throw new Exception("transition is invalid while previous transition is still in progress", transition, from, to, this.state);
    ^
{
  message: 'transition is invalid while previous transition is still in progress',
  transition: 'stop',
  from: 'startConnection',
  to: 'empty',
  current: 'startConnection'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! jira-matrix-bot@0.5.0 start: `node src/app.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the jira-matrix-bot@0.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by grigori-gru** [comment]
Hello! 
It means that you don't have such path to write your logs. Try to change param "filePath" inside your config or just add directory "logs"

**Comment by linuxgoose** [comment]
I swear I added "logs", but it was "log", missing the 's'.

Sigh... Never set up a new service at midnight.

Thanks for your help!
