### ISSUE TITLE
[question] Is it possible to post all messages in one room

### ISSUE THREAD

**Issue by oniksfly** [mobitel-ltd/jira-to-matrix#87]
Setting `features.createRoom` is set to `false` and I'd like to post all notifications in single room. Is it possible to do it?

**Comment by grigori-gru** [comment]
Hello!
All `features` are made for controlling permissible actions of your bot. It helps you to expand or reduce opportunities to create or notify according to events in Jira. 
For example, if you set `false`, your bot will never be able to create room in Matrix when task in Jira creates. But all notifications (new listeners, updating issue status...) will come to rooms which are already made.

**Comment by w1r0x** [comment]
In addition to Grigori comment,
`jira-to-matrix` is not just Jira notifier, it is  [ChatOps](https://www.atlassian.com/blog/it-service-management/inside-atlassian-sre-use-chatops-run-incident-management) system that integrates with Jira like HipChat do this.

**Comment by oniksfly** [comment]
Thanks guys!
