### ISSUE TITLE
Hardcoded username in user request to Jira

### ISSUE THREAD

**Issue by BrotherWarrior** [mobitel-ltd/jira-to-matrix#92]
Why username is hardcoded to `@boom` in user list request?

https://github.com/mobitel-ltd/jira-to-matrix/blob/ee22cb816fa11c2977ec9c17d7e7866fd2258bab/src/matrix/timeline-handler/commands/helper.js#L31

**Comment by grigori-gru** [comment]
Yes, it was not a good idea. But I hae already fixed it in last commit, it's on review now.
